### PR TITLE
Fix failing validation when saving a new node object with associated parents

### PR DESCRIPTION
**Pull request by MarkMT**
This PR resolves issue #20.

### CODE REVIEW

**Comment by MarkMT** [comment]
Closed without comment after 8.5 years?

**Comment by mathieujobin** [comment]
looks like he renamed his master branch to be the main branch, thus PR gets automatically closed.
or maybe we should reopen against the parent repo https://github.com/mleventi/acts-as-dag

**Comment by MarkMT** [comment]
If it's just a rename I might re-open against the main branch. However with the repo appearing to have been abandoned all this time, there may not be any point. Leventi's is even older. In any case, I'm happy using my own fork.

**Comment by mathieujobin** [comment]
I tried reopening #28 as #29 ... we'll see

**Pull request closed without merging**
